/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: database_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./database_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.DatabaseServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.DatabaseServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.RecordRequest,
 *   !proto.Response>}
 */
const methodDescriptor_DatabaseService_AddRecord = new grpc.web.MethodDescriptor(
  '/DatabaseService/AddRecord',
  grpc.web.MethodType.UNARY,
  proto.RecordRequest,
  proto.Response,
  /**
   * @param {!proto.RecordRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Response.deserializeBinary
);


/**
 * @param {!proto.RecordRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.DatabaseServiceClient.prototype.addRecord =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/DatabaseService/AddRecord',
      request,
      metadata || {},
      methodDescriptor_DatabaseService_AddRecord,
      callback);
};


/**
 * @param {!proto.RecordRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Response>}
 *     Promise that resolves to the response
 */
proto.DatabaseServicePromiseClient.prototype.addRecord =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/DatabaseService/AddRecord',
      request,
      metadata || {},
      methodDescriptor_DatabaseService_AddRecord);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.RecordRequest,
 *   !proto.Response>}
 */
const methodDescriptor_DatabaseService_DeleteRecord = new grpc.web.MethodDescriptor(
  '/DatabaseService/DeleteRecord',
  grpc.web.MethodType.UNARY,
  proto.RecordRequest,
  proto.Response,
  /**
   * @param {!proto.RecordRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Response.deserializeBinary
);


/**
 * @param {!proto.RecordRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.DatabaseServiceClient.prototype.deleteRecord =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/DatabaseService/DeleteRecord',
      request,
      metadata || {},
      methodDescriptor_DatabaseService_DeleteRecord,
      callback);
};


/**
 * @param {!proto.RecordRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Response>}
 *     Promise that resolves to the response
 */
proto.DatabaseServicePromiseClient.prototype.deleteRecord =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/DatabaseService/DeleteRecord',
      request,
      metadata || {},
      methodDescriptor_DatabaseService_DeleteRecord);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.StreamRequest,
 *   !proto.RecordList>}
 */
const methodDescriptor_DatabaseService_GetRecords = new grpc.web.MethodDescriptor(
  '/DatabaseService/GetRecords',
  grpc.web.MethodType.UNARY,
  proto.StreamRequest,
  proto.RecordList,
  /**
   * @param {!proto.StreamRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.RecordList.deserializeBinary
);


/**
 * @param {!proto.StreamRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.RecordList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.RecordList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.DatabaseServiceClient.prototype.getRecords =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/DatabaseService/GetRecords',
      request,
      metadata || {},
      methodDescriptor_DatabaseService_GetRecords,
      callback);
};


/**
 * @param {!proto.StreamRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.RecordList>}
 *     Promise that resolves to the response
 */
proto.DatabaseServicePromiseClient.prototype.getRecords =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/DatabaseService/GetRecords',
      request,
      metadata || {},
      methodDescriptor_DatabaseService_GetRecords);
};


module.exports = proto;

